<a href="https://colab.research.google.com/github/khayk5ay/Version-ctrl-with-git/blob/main/HDSC%20Food%20Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [12]:
food_data = pd.read_csv('/FoodBalanceSheets_E_Africa_NOFLAG.csv', error_bad_lines=False, encoding='latin-1')
food_data.isna()
food_data.head(50)

    Area Code     Area  Item Code  ...     Y2016     Y2017     Y2018
0           4  Algeria       2501  ...  40551.00  41389.00  42228.00
1           4  Algeria       2501  ...      0.00      0.00      0.00
2           4  Algeria       2901  ...   3372.00   3341.00   3322.00
3           4  Algeria       2901  ...     94.72     92.82     91.83
4           4  Algeria       2901  ...     77.40     80.19     77.28
5           4  Algeria       2903  ...   2941.00   2921.00   2932.00
6           4  Algeria       2903  ...     67.37     66.11     67.10
7           4  Algeria       2903  ...     52.04     55.59     54.57
8           4  Algeria       2941  ...    431.00    421.00    390.00
9           4  Algeria       2941  ...     27.35     26.71     24.73
10          4  Algeria       2941  ...     25.37     24.60     22.71
11          4  Algeria       2905  ...   3445.00   3478.00   6065.00
12          4  Algeria       2905  ...  13523.00  13039.00  13182.00
13          4  Algeria       2905  ...    905.00    705.00   2226.00
14          4  Algeria       2905  ...      7.00     10.00     17.00
15          4  Algeria       2905  ...  16056.00  15803.00  17004.00
16          4  Algeria       2905  ...   4838.00   4667.00   5266.00
17          4  Algeria       2905  ...    197.00    202.00    278.00
18          4  Algeria       2905  ...   1148.00   1121.00   1253.00
19          4  Algeria       2905  ...     37.00     33.00     44.00
20          4  Algeria       2905  ...    835.00    840.00    951.00
21          4  Algeria       2905  ...      0.00      0.00     -8.00
22          4  Algeria       2905  ...   9001.00   8941.00   9219.00
23          4  Algeria       2905  ...    221.98    216.02    218.31
24          4  Algeria       2905  ...   1699.00   1656.00   1672.00
25          4  Algeria       2905  ...     50.01     48.86     49.36
26          4  Algeria       2905  ...      6.83      6.63      6.58
27          4  Algeria       2511  ...   2440.00   2437.00   3981.00
28          4  Algeria       2511  ...   8255.00   8105.00   8434.00
29          4  Algeria       2511  ...    731.00    546.00   1927.00
30          4  Algeria       2511  ...      6.00     10.00     17.00
31          4  Algeria       2511  ...   9958.00   9987.00  10472.00
32          4  Algeria       2511  ...    584.00    587.00    665.00
33          4  Algeria       2511  ...    123.00    123.00    201.00
34          4  Algeria       2511  ...    747.00    736.00    868.00
35          4  Algeria       2511  ...      0.00      0.00      0.00
36          4  Algeria       2511  ...    835.00    840.00    951.00
37          4  Algeria       2511  ...      0.00      0.00     -8.00
38          4  Algeria       2511  ...   7670.00   7701.00   7795.00
39          4  Algeria       2511  ...    189.14    186.07    184.58
40          4  Algeria       2511  ...   1453.00   1430.00   1419.00
41          4  Algeria       2511  ...     43.85     43.18     42.85
42          4  Algeria       2511  ...      5.37      5.25      5.12
43          4  Algeria       2805  ...      0.00      0.00      0.00
44          4  Algeria       2805  ...    162.00    190.00    207.00
45          4  Algeria       2805  ...     -4.00     17.00     37.00
46          4  Algeria       2805  ...      0.00      0.00      0.00
47          4  Algeria       2805  ...    167.00    173.00    170.00
48          4  Algeria       2805  ...      1.00      2.00      0.00
49          4  Algeria       2805  ...      0.00      0.00      0.00

[50 rows x 12 columns]

In [ ]:
#question

In [29]:
#question 20
len(food_data.groupby('Area'))

49